### ISSUE TITLE
Set up Circle CI for automated deployments with CloudFormation

### ISSUE THREAD

**Issue by arunasank** [hotosm/tasking-manager#1444]
Ref: https://github.com/hotosm/tasking-manager/issues/1395

To complete the new setup, we must:
* [x] Migrate to Circle v2
* [x] Set up automated deployments for the Tasking Manager with circle ci + cloudformation. From https://github.com/mapbox/cfn-config

>  
```
-f, --force             perform a create/update/delete command without any
                            prompting, accepting all defaults
```

So, we can use preset templates on S3 + the `-f` option on circle ci to do automated deployments much like we were doing with Elastic Beanstalk.

**Comment by arunasank** [comment]
cc/ @dakotabenjamin @hotosm/tech

**Comment by dakotabenjamin** [comment]
From our slack convo: I had some confusion about the software deployment strategy that was cleared up (thanks @arunasank ) which I will describe here to illustrate some problems that need to be addressed. 

Using cfn-config as the deployment strategy, there is a GitSha parameter which will be different each time deployment happens. This hash corresponds to the commit being deployed and ensures a change in the LaunchConfiguration (because the UserData clones the Tasking Manager repo based on the commit). When this happens, the LaunchConfiguration will be replaces thus replacing all the EC2 instances with the new UserData and the new code. 

The problem therein is that there will not be 100% uptime during a deployment. There are ways around this see #issue ), but with in-place or rolling updates we have to address a more pressing issue around the database. When pushing software updates that update the database (i.e. a new alembic revision) there is a risk of mismatch between the running instances and the database. I'm not exactly sure what this failure will look like, but in the past with elastic beanstalk there have been issues where alembic update has failed due version mismatch. In any case we should avoid having multiple versions of tasking manager connected to a single database.

**Comment by dakotabenjamin** [comment]
Looking for some advice on how to properly store the environment variables below:
```
      - run: 
          name: Create config file
          command: |
            printf '{"GitSha":"$CIRCLE_SHA1","Environment":"production","DBSnapshot":"$DB_SNAPSHOT","MasterUsername":"$MASTER_USERNAME","MasterPassword":"$MASTER_PASSWORD","OSMConsumerKey":"$OSM_CONSUMER_KEY","OSMConsumerSecret":"$OSM_CONSUMER_SECRET","TaskingManagerSecret":"$TASKINGMANAGER_SECRET","TaskingManagerEnv":"$TASKINGMANAGER_ENV","TaskingManagerSMTPHost":"$TASKINGMANAGER_SMTP_HOST","TaskingManagerSMTPPassword":"$TASKINGMANAGER_SMTP_PASSWORD","TaskingManagerSMTPUser":"$TASKINGMANAGER_SMTP_USER","DatabaseSize":"$DATABASE_SIZE","ELBSubnets":"$ELB_SUBNETS","SSLCertificateIdentifier":"$SSL_CERTIFICATE_ID","RDSUrl":"$RDS_URL"}' > cfn-config-production.json
      - deploy:
          name: Deploy to Production
          command: cfn-config update production cfn-config-production.json -f -c hot-cfn-config -t hot-cfn-config
```

These keys could be stored in circleci itself using the UI. Or they could be pulled from a remote env file maybe in the hot-cfn-config. Ideally they would exist in a private repo under source control and could be updated independently if needed.
