### ISSUE TITLE
Improve docker to use alternate ports

### ISSUE THREAD

**Issue by robsavoye** [hotosm/tasking-manager#6183]
Right now to run TM locally if requires both port 5432 and 80 to be open. If you do this on a system with both of these running already, the docker image won't work. Several other HOT projects support using alternate ports for local development.

**Comment by spwoodcock** [comment]
An easy way to do that would be environment variables in the compose file.

```yaml
service:
  db:
    ports:
      - ${POSTGRES_PORT:-5432}:5432
```

So the default is 5432, but the user can either put port in their .env file, or configure on the command line: `POSTGRES_PORT=9999 docker compose up -d`
