### ISSUE TITLE
Implement matrix testing for multiple versions of node

### ISSUE THREAD

**Issue by dakotabenjamin** [hotosm/tasking-manager#6254]
**Is your feature request related to a problem? Please describe.**
For better dependency management, it would be good to test against multiple versions of node. This will help us have higher information about future updates and give people trying to run their own TM info about which versions are stable. 

**Describe the solution you'd like**
circleci supports testing against multiple versions, something like this: https://circleci.com/developer/orbs/orb/circleci/node#usage-run_matrix_testing

```
version: '2.1'
orbs:
  node: circleci/node@x.y
workflows:
  matrix-tests:
    jobs:
      - node/test:
          matrix:
            parameters:
              version:
                - 18.19.1
                - 20.11.0
                - 21.6.2
```
This is only an example. We would need to add logic such that only the version we are using in deployment is required for tests to pass.
